### ISSUE TITLE
Missing flags to run cordinator readme example 

### ISSUE THREAD

**Issue by pedrojlsilva** [xainag/xain-fl#236]
I tried to run the readme example without docker, inside a virtuaenv configured with python3 and i had this error:
```bash
cli.py: error: the following arguments are required: --storage-endpoint, --storage-bucket, --storage-key-id, --storage-secret-access-key
```
There is something missing in the readme? thank you!!

**Comment by Robert-Steiner** [comment]
Hi Pedro, thank you for opening this issue. 

The error that you got has something to do with the storage of the aggregated weights. In our the last release, we added the feature to persist the aggregated weights locally. For that, we need to start an additional dependency [minio](https://min.io/) in order to run the coordinator. You can setup your own minio server or you can try out the docker-compose development setup which should start a coordinator (and all dependencies) by just running `docker-compose -f docker-compose-dev.yml up`. 

Please note that the first build of the docker image can take some time (up to 15min). If the docker-compose setup does not work, please let me know.

**Comment by pedrojlsilva** [comment]
Thank you Robert, I'll try this asap and give you an answer

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue/solution relates to an old version (`v0.6.0`) of the python coordinator that is no longer maintained.

If there is a similar issue in the upcoming version, please open a new ticket instead of opening it again.

Thank you!
