### ISSUE TITLE
Expose a proper REST API

### ISSUE THREAD

**Issue by little-dude** [xainag/xain-fl#327]
Currently our API doesn't really adhere to REST.

- an obvious improvement would be to use json for all the messages (except weights)
- we should also return proper status codes instead of a 404 when an issue occurs
- cleanup the paths (the client ids and token perhaps belong to the headers instead)

**Comment by Robert-Steiner** [comment]
I'm closing this issue because the issue relates to an old version (`v0.8.0`) of the rust coordinator that is no longer maintained. The API has changed radically in the new upcoming version so that many of the problems mentioned here no longer apply.

If there is a similar issue in the upcoming version, please open a new ticket instead of opening it again.
